In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [2]:
df=pd.read_csv("Jobs.csv")

In [3]:
df

Company                  Job     Degree  Salary_more_than_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [4]:
df.head()

Company                  Job     Degree  Salary_more_than_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [5]:
inputs=df.drop('Salary_more_than_100k',axis='columns')

In [6]:
target=df['Salary_more_than_100k']

In [7]:
inputs

Company                  Job     Degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [8]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: Salary_more_than_100k, dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [15]:
inputs['company_s']=le_company.fit_transform(inputs['Company'])
inputs['job_s']=le_job.fit_transform(inputs['Job'])
inputs['degree_s']=le_degree.fit_transform(inputs['Degree'])
inputs.head()

Company                  Job     Degree  company_s  job_s  degree_s
0  google      sales executive  bachelors          2      2         0
1  google      sales executive    masters          2      2         1
2  google     business manager  bachelors          2      0         0
3  google     business manager    masters          2      0         1
4  google  computer programmer  bachelors          2      1         0

In [16]:
inputs_s=inputs.drop(['Company','Job','Degree'],axis='columns')
inputs_s

company_s  job_s  degree_s
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [17]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [18]:
model.fit(inputs_s,target)

DecisionTreeClassifier()

In [19]:
model.score(inputs_s,target)

1.0

In [22]:
model.predict([[2,2,1]])

array([0], dtype=int64)

# Titanic.csv

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [22]:
df=pd.read_csv("titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [44]:
targets=df["Survived"]
targets=targets.head(20)

In [24]:
inputs=df.drop(["PassengerId","Name","SibSp","Parch","Ticket","Cabin","Embarked"],axis="columns")
inputs.head(10)

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500
5         0       3    male   NaN   8.4583
6         0       1    male  54.0  51.8625
7         0       3    male   2.0  21.0750
8         1       3  female  27.0  11.1333
9         1       2  female  14.0  30.0708

In [25]:
from sklearn.preprocessing import LabelEncoder
le_Sex=LabelEncoder()
inputs['Sex_s']=le_Sex.fit_transform(inputs["Sex"])

In [26]:
inputs.head(10)

Survived  Pclass     Sex   Age     Fare  Sex_s
0         0       3    male  22.0   7.2500      1
1         1       1  female  38.0  71.2833      0
2         1       3  female  26.0   7.9250      0
3         1       1  female  35.0  53.1000      0
4         0       3    male  35.0   8.0500      1
5         0       3    male   NaN   8.4583      1
6         0       1    male  54.0  51.8625      1
7         0       3    male   2.0  21.0750      1
8         1       3  female  27.0  11.1333      0
9         1       2  female  14.0  30.0708      0

In [27]:
inputs=inputs.drop(['Sex'],axis='columns').head(20)

In [28]:
inputs

Survived  Pclass   Age     Fare  Sex_s
0          0       3  22.0   7.2500      1
1          1       1  38.0  71.2833      0
2          1       3  26.0   7.9250      0
3          1       1  35.0  53.1000      0
4          0       3  35.0   8.0500      1
5          0       3   NaN   8.4583      1
6          0       1  54.0  51.8625      1
7          0       3   2.0  21.0750      1
8          1       3  27.0  11.1333      0
9          1       2  14.0  30.0708      0
10         1       3   4.0  16.7000      0
11         1       1  58.0  26.5500      0
12         0       3  20.0   8.0500      1
13         0       3  39.0  31.2750      1
14         0       3  14.0   7.8542      0
15         1       2  55.0  16.0000      0
16         0       3   2.0  29.1250      1
17         1       2   NaN  13.0000      1
18         0       3  31.0  18.0000      0
19         1       3   NaN   7.2250      0

In [46]:
inputs=inputs.drop("Survived",axis="columns")

In [47]:
inputs.Age=inputs.Age.fillna(5)
inputs

Pclass   Age     Fare  Sex_s
0        3  22.0   7.2500      1
1        1  38.0  71.2833      0
2        3  26.0   7.9250      0
3        1  35.0  53.1000      0
4        3  35.0   8.0500      1
5        3   5.0   8.4583      1
6        1  54.0  51.8625      1
7        3   2.0  21.0750      1
8        3  27.0  11.1333      0
9        2  14.0  30.0708      0
10       3   4.0  16.7000      0
11       1  58.0  26.5500      0
12       3  20.0   8.0500      1
13       3  39.0  31.2750      1
14       3  14.0   7.8542      0
15       2  55.0  16.0000      0
16       3   2.0  29.1250      1
17       2   5.0  13.0000      1
18       3  31.0  18.0000      0
19       3   5.0   7.2250      0

In [51]:
from sklearn import tree

In [48]:
model=tree.DecisionTreeClassifier()

In [49]:
model.fit(inputs,targets)

DecisionTreeClassifier()

In [53]:
model.score(inputs,targets)

1.0

In [54]:
model.predict([[1,38,71,0]])

array([1], dtype=int64)

In [55]:
model.predict([[1,38,71,1]])

array([0], dtype=int64)

In [56]:
model.predict([[1,3,71,0]])

array([1], dtype=int64)

In [57]:
model.predict([[1,3,71,1]])

array([1], dtype=int64)

ValueError: Classification metrics can't handle a mix of continuous-multioutput and binary targets